### ISSUE TITLE
MIME type error sending mail

### ISSUE THREAD

**Issue by atrujillofalcon** [bbottema/simple-java-mail#149] opened 2018-06-20 14:09 UTC
Hi, I'm having troubles to send mail using a predefined Session instance in a Tomcat server. When mail is to be sent I got this error:
```

java.lang.RuntimeException: no object DCH for MIME type multipart/mixed; __	boundary="----=_Part_3_1506400929.1529502766000" [Sanitized]
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEML(EmailConverter.java:202)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:262)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:239)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:230)
	at com.cetelem.web.auto.simulator.portlet.service.impl.LiferayMailService.sendMail(LiferayMailService.kt:51)
	at com.cetelem.web.auto.simulator.portlet.service.definition.MailService$DefaultImpls.sendMail$default(MailService.kt:6)
	at com.cetelem.web.auto.simulator.portlet.controller.AutoSimulatorPortletViewController.sendMail(AutoSimulatorPortletViewController.kt:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:180)
	at 
.
.
.
.

Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed; __	boundary="----=_Part_3_1506400929.1529502766000" [Sanitized]
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:896)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1350)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1683)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1659)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEML(EmailConverter.java:198)
```

In my project is mandatory to send emails reusing the predefined session instance. My mailer building is like this:

```java
val emailToSend = EmailBuilder
                .startingBlank()
                .toMultiple(toAddresses)
                .from(replyAddress)
                .withSubject(subject)
                .withHTMLText(textHTML)
                .buildEmail()

        val mailer = MailerBuilder
                .usingSession(emailConfig.session)
                .withDebugLogging(true)
                .buildMailer()

        mailer.sendMail(emailToSend)
```

**Comment by bbottema** [comment] 2018-06-30 06:22
I need a little bit more context.

1. Does it work with a Session configured through Simple Java Mail?
2. What is the structure of the email?
3. What types of attachments / embedded images are there?

**Comment by atrujillofalcon** [comment] 2018-07-02 21:09
Thanks for reply. 

1- I get a preconfigured Session provided from a portal CMS.
2- What do you mean by structure? I'm building the mail using the HTML generated by any MJML template (see https://mjml.io/try-it-live)
3- Fails even without embedded images.

I attach a simple generated HTML that fails when I try to use simple-java-mail.

Greetings!


[dummy_email.zip](https://github.com/bbottema/simple-java-mail/files/2156803/dummy_email.zip)

**Comment by bbottema** [comment] 2018-07-09 20:10
So what I mean with structure is how are you building the email. But from your comment I understand it is an email with HTML content, not plain text content, no attachments and no embedded images.

And still you are getting this error. I've seen the error "no object DCH for MIME type multipart/mixed" happening due to class loader issues. Are you using something like Groovy, or OSGi? The problem, as I understand it, is that the relevant internal JavaMail classes (from javax.activation, javax.mail, javax.mail.internet) that set these MIME type handlers should be loaded using the same classloader as was used for the code utilizing the MimeMessage (in your case using it to convert to EML) or else these MIME type handlers will be missing somehow.

**Comment by atrujillofalcon** [comment] 2018-07-09 21:57
Thanks for the reply. I am indeed running my application in an OSGI environment that provide me the Session instance. So I understand I won't be able to use the library for compatibility reasons at this time.

**Comment by bbottema** [comment] 2018-07-10 19:50
Well.... you can redefine all the handlers manually, like done [@castortech did](https://github.com/bbottema/simple-java-mail/issues/147#issuecomment-401538780):

```java
MailcapCommandMap mc = (MailcapCommandMap) CommandMap.getDefaultCommandMap();
String[] mimeTypes = mc.getNativeCommands("multipart/*");
if (mimeTypes == null || mimeTypes.length < 1) {
	mc.addMailcap("text/html;; x-java-content-handler=com.sun.mail.handlers.text_html"); 
	mc.addMailcap("text/xml;; x-java-content-handler=com.sun.mail.handlers.text_xml"); 
	mc.addMailcap("text/plain;; x-java-content-handler=com.sun.mail.handlers.text_plain"); 
	mc.addMailcap("multipart/*;; x-java-content-handler=com.sun.mail.handlers.multipart_mixed"); 
	mc.addMailcap("message/rfc822;; x-java-content-handler=com.sun.mail.handlers.message_rfc822");		
}
```

**Comment by bbottema** [comment] 2018-07-10 20:06
Closing this as a duplicate of #147. If I can support OSGi without rewriting Simple Java Mail, please let me know. Otherwise, try looking into something like AOP to solve OSGi's classloading problem.

**Closed by bbottema** 2018-07-10 20:06 UTC
Labels: duplicate, invalid

**Comment by castortech** [comment] 2018-07-10 20:10
As stated we have this issue and have implemented a work around for now. I am still planning on proposing a more generic solution, but if you look at the referenced issue it shows the change that was needed. You can always contact me should you have any questions.

**Comment by bbottema** [comment] 2018-07-10 20:11
Now that I think about it, perhaps Simple Java Mail can simply check if these handlers are set and always manually set them if missing.

Would that solve your problem @castortech and @atrujillofalcon? That would be a simple fix and I don't except Java Mail to modify this part of the framework any time soon.
