### ISSUE TITLE
.testConnection() blocks indefinitely

### ISSUE THREAD

**Issue by sddavis** [bbottema/simple-java-mail#189] opened 2018-12-12 21:49 UTC
A call to org.simplejavamail.mailer.Mailer.testConnection() with a session timeout of 60s blocked for 3 hours before the user gave up and killed the process. This was using SMTP on port 25 with simple-java-mail-5.0.3.jar.

Thread dump:

` at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:126)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
    at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:104)
    at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2425)
    at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172)
    at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:726)
    at javax.mail.Service.connect(Service.java:388)
    at javax.mail.Service.connect(Service.java:246)
    at javax.mail.Service.connect(Service.java:195)
    at org.simplejavamail.mailer.internal.mailsender.MailSender.testConnection(MailSender.java:380)
    at org.simplejavamail.mailer.Mailer.testConnection(Mailer.java:222)`

**Comment by sddavis** [comment] 2018-12-12 21:51
I see that at https://github.com/bbottema/simple-java-mail it says "You can now test the connection to the SMTP server" in v5.1.0 with a link to https://github.com/bbottema/simple-java-mail/issues/179, which seems completely unrelated to testing connections. But the test connection feature is present in v5.0.3, so I don't understand what this means. 

Did something related to testing connections change in v5.1.0 that might help here?

**Comment by sddavis** [comment] 2018-12-12 21:57
Possibly related to https://github.com/bbottema/simple-java-mail/issues/182?

**Comment by bbottema** [comment] 2018-12-17 16:03
> Possibly related to #182?

I agree, this is probably related.

Are you able to get the timeout working with good old manual Session properties?

**Comment by sddavis** [comment] 2018-12-17 23:43
I have not been able to reproduce the problem myself. I don't know what condition triggers the timeout being ignored.

**Comment by bmuskalla** [comment] 2019-01-09 14:21
I've been able to reproduce this issue using a plain socket server that does not respond at all. I can verify that using the manual session properties works. Here is a test case to reproduce both ways:
https://gist.github.com/bmuskalla/17d789716494d8ceb331bd02fb45c9dd

I think the problem is that MailSender#configureSessionWithTimeout is only ever called by #send but not by test connection. This leads to a session for connection tests without the timeouts. 
Happy to provide a pull request with a fix if you can point me to the location where I can get the parent pom (maven-master-project) from.

**Comment by bbottema** [comment] 2019-01-09 15:01
Ahh, I was not thinking of this as a problem specific to `testConnection`. Your assessment is probably correct, @bmuskalla. For this I would create a _hotfix_ branch off of _master_ to create a patch for this. The master is not yet modularized, so no parent POM needed there.

**Comment by bbottema** [comment] 2019-01-09 15:09
Started working on a fix...

**Comment by bbottema** [comment] 2019-01-09 20:13
Fix released in 5.1.2. Please verify, @sddavis

**Closed by bbottema** 2019-01-09 20:13 UTC
Labels: Priority-High, bug

**Comment by bbottema** [comment] 2019-01-10 15:32
Excellent, thanks for the report and the work!
