### ISSUE TITLE
Source not included in maven release for email validation

### ISSUE THREAD

**Issue by CodeMason** [bbottema/simple-java-mail#122] opened 2018-01-01 15:35 UTC
The entire package, `org.hazlewood.connor.bottema.emailaddress.simplejavamail` doesn't exist in the latest 5.0RC sources.

If one downloads the sources from https://github.com/bbottema/email-rfc2822-validator, the source for `EmailAddressValidator` doesn't match the decompiled classes from simple-java-mail.

Of note, the package is also different between the two projects.

**Comment by bbottema** [comment] 2018-01-02 07:38
This is by design. To avoid maven dependencies on micro-libraries, email-rfc2822-validator is being [shaded](https://maven.apache.org/plugins/maven-shade-plugin/index.html) into the resulting jar. This is possible, because that library is managed by myself as well.

Similarly DKIM was included as well before 5.0.0.rc1, but because it is an external library, it is not included in the simple-java-mail JAR.

**Comment by bbottema** [comment] 2018-01-02 07:42
I am considering turning it into a proper dependency as well, though. Thanks for refreshing my memory.

**Comment by bbottema** [comment] 2018-02-14 15:22
Will be in 5.0.0

**Closed by bbottema** 2018-02-14 15:22 UTC
Labels: invalid
