### ISSUE TITLE
Issue with attachments sent to certain email providers (targets)

### ISSUE THREAD

**Issue by staniko** [bbottema/simple-java-mail#231] opened 2019-10-18 15:53 UTC
We discovered, that for certain email providers not all attachments are working, when they contain special characters or blanks e.g. "Köln Ausflugsziel.pdf". Gmail can handle this, but incamail.ch for example not. 

We solved this by patching the MimeMessageHelper.java with following line (escaping the fileName and taking the filename variable also for the name attribute, because if non US-ASCII chars are used in attachment name, the attachment extension is changed to .dat. This happens maybe because Simple Java Mail always uses application/octet-stream as Content-Type of attachments instead of application/pdf or image/png, etc.

[MimeMessageHelper.java:240](https://github.com/bbottema/simple-java-mail/blob/5cc2b6b37d03a507275bd4585d96c9c3fc9d0f5a/modules/simple-java-mail/src/main/java/org/simplejavamail/converter/internal/mimemessage/MimeMessageHelper.java#L240):
`attachmentPart.setHeader("Content-Type", contentType + "; filename=\"" + fileName + "\"; name=\"" + fileName + "\"");`

Would be great if someone can crosscheck this and we add it to the main code. For us it works now with all kinds of attachments to various providers.

Best regards

Stan

**Comment by bbottema** [comment] 2019-10-20 11:09
Interesting since that was recently changed to handle white spaces, which I think takes care of escaping the name as well. Which version are you on, because this was implemented in 5.4.0 (see #226).

I'm not sure using the filename for name is a good idea though. There is some logic to determine what the sender had meant to use, but for 6.0.0 in the develop branch a bug _was_ fixed regarding determine the extension (#151).

I created a new branch off master for you with just that change from develop. Maybe you can try that patch in your branch and see if it fixes your problem.

* https://github.com/bbottema/simple-java-mail/tree/attachment-naming-conversion-tweak

> because if non US-ASCII chars are used in attachment name, the attachment extension is changed to .dat

This is odd behavior, can you show me where this happens?

**Comment by staniko** [comment] 2019-10-25 13:34
Thanks a lot, we check it within the next 3 weeks and respond then. Maybe the .dat issue is also resolved with the latest version.

**Comment by bbottema** [comment] 2019-11-27 20:59
Any news?

**Comment by bbottema** [comment] 2019-12-03 11:47
Closing this issue as invalid, as I can't proceed without more information. I'll keep the branch around for you for some more time.

I'll be happy to reopen once you can tell me more.

**Closed by bbottema** 2019-12-03 11:47 UTC
Labels: Priority-Medium, bug, need-user-input

**Comment by pbernet** [comment] 2020-03-26 06:42
Thanks for maintaining this convenient library.
I can confirm that upgrading to the latest version 6.0.3 fixed the issue. This works with all our email providers:
```
mailBuilder.withAttachment("Köln Ausflugsziel.pdf", new FileDataSource(myFile));
```
