### ISSUE TITLE
Third party error

### ISSUE THREAD

**Issue by richman666888** [bbottema/simple-java-mail#420] opened 2022-09-24 02:04 UTC
Third-party error. why? and it's not an SMTP server thing. I use PHP is OK.

** kotlin code :**
val email: Email = EmailBuilder.startingBlank()
.from("lollypop", "service@ali.com")
.to("C. Cane", "gtegegght@hotmail.com")
.cc("notification999@163.com")
.withSubject("hey")
.withPlainText("We should meet up! ;)")
.buildEmail()
val mailer: Mailer = MailerBuilder
.withSMTPServer("smtpdm-ap-southeast-1.yun.com", 80, "info@888.com", "888")
.buildMailer()
mailer.sendMail(email).await()

**error detail :**

{
"msg": "Failed to send email [1158311587.1.1663815840084@pal], reason: Third party error",
"trace": "[org.simplejavamail.mailer.internal.SendMailClosure.handleException(SendMailClosure.java:97) -> , org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:89) -> , org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56) -> , org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345) -> , org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331) -> , com.queen.common.EmailKt.mail1(email.kt:31) -> , com.queen.route.Test1Kt$test1$18.invokeSuspend(test1.kt:218) -> , com.queen.route.Test1Kt$test1$18.invoke(test1.kt) -> , com.queen.route.Test1Kt$test1$18.invoke(test1.kt) -> , io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:127) -> , io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:85) -> , io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:105) -> , io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:83) -> , io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:471) -> , io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt) -> , io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt) -> , io.ktor.util.debug.ContextUtilsKt.addToContextInDebugMode(ContextUtils.kt:18) -> , io.ktor.server.routing.Routing.executeResult(Routing.kt:171) -> , io.ktor.server.routing.Routing.interceptor(Routing.kt:47) -> , io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:122) -> , io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt) -> , io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt) -> , io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:127) -> , io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:85) -> , io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:122) -> , io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt) -> , io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt) -> , io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:127) -> , io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:85) -> , io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:105) -> , io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:83) -> , io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:471) -> , io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt) -> , io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt) -> , io.ktor.util.debug.ContextUtilsKt.addToContextInDebugMode(ContextUtils.kt:18) -> , io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118) -> , io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt) -> , io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt) -> , io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:127) -> , io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:85) -> , io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:105) -> , io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:83) -> , io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:471) -> , io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt) -> , io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt) -> , io.ktor.util.debug.ContextUtilsKt.addToContextInDebugMode(ContextUtils.kt:18) -> , io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:121) -> , io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt) -> , io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt) -> , kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) -> , kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) -> , kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) -> , kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) -> , kotlinx.coroutines.BuildersKt.launch(Unknown Source) -> , io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:41) -> , io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:33) -> , io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) -> , io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) -> , io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) -> , io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) -> , io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) -> , io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) -> , io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) -> , io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) -> , io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:258) -> , io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) -> , java.base/java.lang.Thread.run(Thread.java:833) -> ]"
}

**Comment by bbottema** [comment] 2022-12-14 20:29
3rd Party error comes from the underlying Jakarta Mail library. It can be anything, from a connection issue, authentication to an error during transport sending, or closing the connection. It's impossible to see for me though, because I think the cause exception seems to be missing in your log (I only see the stacktrace of the top-level exception). Where's the caused-by stacktrace?

**Closed by bbottema** 2022-12-14 20:29 UTC
