### ISSUE TITLE
simple-java-mail from oracle

### ISSUE THREAD

**Issue by PeterKing71** [bbottema/simple-java-mail#60] opened 2017-01-09 11:01 UTC
Hi bbottema, 

Try to use Simple Java Mail 3.1.1 in Oracle Database but get errors with simple-java-mail-3.1.1.jar about 
"referenced object TMP_JAVAMAIL.org/codemonkey/simplejavamail/Mailer could not be resolved"

Any experience with try to install in Oracle RDBMS with 1.6.0_115 Java version ?

Regards

**Comment by bbottema** [comment] 2017-01-09 12:07
I have no idea what TMP_JAVAMAIL.org is supposed to be.

**Comment by PeterKing71** [comment] 2017-01-09 16:20
Hi Bbottema, 

Thanks in advance, 
Seems that doesn't resolve class org/codemonkey/simplejavamail/Mailer$1, we try with these jar files: 

-rw-r--r--  1 oracle oinstall  62983 Jan  9 11:28 activation-1.1.jar
-rw-r--r--  1 oracle oinstall 603571 Jan  9 11:28 javax.mail-1.5.5.jar
-rw-r--r--  1 oracle oinstall 261382 Jul 30 20:30 mailapi-1.4.4.jar
-rw-r--r--  1 oracle oinstall  52195 Jul 30 20:30 smtp-1.4.4.jar
-rw-r--r--  1 oracle oinstall  88116 Jan  9 11:28 simple-java-mail-3.1.1.jar

And when try to load simple-java-mail-3.1.1.jar file get the next error: 

[oracle@orades]$ $ORACLE_HOME/bin/loadjava -user TMP_JAVAMAIL/DATADEC -grant public -resolve simple-java-mail-3.1.1.jar
errors   : class org/codemonkey/simplejavamail/Mailer$1
    ORA-29534: referenced object TMP_JAVAMAIL.org/codemonkey/simplejavamail/Mailer could not be resolved
errors   : class org/codemonkey/simplejavamail/Mailer$MimeEmailMessageWrapper
    ORA-29521: referenced name org/slf4j/Logger could not be found
errors   : class org/codemonkey/simplejavamail/Mailer
    ORA-29521: referenced name org/slf4j/Logger could not be found
    ORA-29521: referenced name org/slf4j/LoggerFactory could not be found
errors   : class net/markenwerk/utils/mail/dkim/DkimSigner
    ORA-29521: referenced name net/markenwerk/utils/data/fetcher/BufferedFetcher could not be found
    ORA-29521: referenced name net/iharder/Base64 could not be found
errors   : class net/markenwerk/utils/mail/dkim/DomainKeyUtil
    ORA-29534: referenced object TMP_JAVAMAIL.net/markenwerk/utils/mail/dkim/DomainKey could not be resolved
errors   : class net/markenwerk/utils/mail/dkim/DomainKey
    ORA-29521: referenced name net/iharder/Base64 could not be found
errors   : class net/markenwerk/utils/mail/dkim/DkimMessage
    ORA-29521: referenced name net/markenwerk/utils/data/fetcher/BufferedFetcher could not be found
The following operations failed
    class org/codemonkey/simplejavamail/Mailer$1: resolution
    class org/codemonkey/simplejavamail/Mailer$MimeEmailMessageWrapper: resolution
    class org/codemonkey/simplejavamail/Mailer: resolution
    class net/markenwerk/utils/mail/dkim/DkimSigner: resolution
    class net/markenwerk/utils/mail/dkim/DomainKeyUtil: resolution
    class net/markenwerk/utils/mail/dkim/DomainKey: resolution
    class net/markenwerk/utils/mail/dkim/DkimMessage: resolution
exiting  : Failures occurred during processing

Regards

**Comment by bbottema** [comment] 2017-01-10 06:27
There's something strange going on, because all the import statements are malformed with a pretending TMP_JAVAMAIL.net. Of course this doesn't exist. No idea what Oracle is doing here. For 3.1.1 you do need to include SLF4J though as dependency.

**Comment by PeterKing71** [comment] 2017-01-10 14:57
Hi, 

I try to view what problem in Oracle and inform you.

Regards

**Comment by bbottema** [comment] 2017-01-10 15:02
I had updated my comment from my phone, but the app didn't register it.

I think the issue is that 3.1.1 depends on SLF4J and it seems to be missing in your application. Because of that, Simple Java Mail afils to load and so the import statements cannot be resolved.

Have you added SLF4J yet?

**Comment by PeterKing71** [comment] 2017-01-10 17:36
With slf4j-api-1.7.13.jar seems that "org/slf4j/impl/StaticLoggerBinder" doesn't exist.

**Comment by bbottema** [comment] 2017-01-27 22:35
You need to properly configure SLF4J. Please research SLF4J and add the appropriate dependencies (SLF4J API and either SLF4J impl or the bridges to Log4J or LogBack). Also see http://www.simplejavamail.org/#/debugging.

I'm closing this issue as unsolvable by Simple Java Mail.

**Closed by bbottema** 2017-01-27 22:35 UTC
