### ISSUE TITLE
unknown content transfer encoder: 8bit

### ISSUE THREAD

**Issue by RevoutIT** [bbottema/simple-java-mail#485] opened 2023-12-11 16:44 UTC
Hello, if an email has content transfer encoding: 8bit, an exception is thrown at EmailConverter.mimeMessageToEmail(mimeMessage): unknown content transfer encoder: 8bit. Can this please be changed so that encoder is ignored in this case?

https://learn.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa563055(v=exchg.140)

Thank you!

**Comment by bbottema** [comment] 2023-12-12 16:02
Do you have an example message I can work with?

**Comment by RevoutIT** [comment] 2023-12-12 16:40
Hello, here is the email that caused the problem.
[test8Bit..zip](https://github.com/bbottema/simple-java-mail/files/13650813/test8Bit.zip)

**Comment by bbottema** [comment] 2023-12-12 18:06
Which version are you one? I'm having no issues with 8.x.x.

**Comment by RevoutIT** [comment] 2023-12-12 18:27
8.3.2

**Comment by bbottema** [comment] 2023-12-12 19:46
I'm not able to reproduce the problem with 8.3.2 and your example message, unfortunately. Do you have a stack trace?

**Comment by RevoutIT** [comment] 2023-12-12 19:58
java.lang.IllegalArgumentException: unknown content transfer encoder: 8bit 
	at org.simplejavamail.api.email.ContentTransferEncoding.lambda$byEncoder$1(ContentTransferEncoding.java:55)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.simplejavamail.api.email.ContentTransferEncoding.byEncoder(ContentTransferEncoding.java:55)
	at org.simplejavamail.converter.EmailConverter.buildEmailFromMimeMessage(EmailConverter.java:673)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:139)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:125)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmail(EmailConverter.java:101)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmail(EmailConverter.java:93)

**Comment by bbottema** [comment] 2023-12-12 20:23
I have no idea how that would even be possible. At any rate, I can't reproduce it with 8.3.2, and I've expanded the junit tests to test this particular case, which also builds [fine](https://app.circleci.com/pipelines/github/bbottema/simple-java-mail/775/workflows/2da19939-a2de-4e1d-8fa9-33decc5b0819/jobs/695/parallel-runs/0/steps/0-103) in the pipeline. I'm not sure what else I can do here.

No clue what's going on in your case. Maybe something related to reflection code on your end? Or a server fooling around with class loaders? Surprising indeed. I don't see any other way than to close this as user error, even if the cause is unknown. I'll happily reopen if you come up with more data (perhaps you're able to debug into the class and see what is happening).

**Closed by bbottema** 2023-12-12 20:23 UTC
Labels: need-user-input
