### ISSUE TITLE
Using .to() .cc() .bcc() from fluent builder API causes duplicated headers

### ISSUE THREAD

**Issue by holgerstolzenberg** [bbottema/simple-java-mail#26] opened 2016-02-05 11:57 UTC
I used the fluent builder API in order to add multiple recipients:

```java
final Email email = new Email.Builder()
        .from(…)
        .subject(…)
        .text(…)
        .to("ONE", "one@host.com")
        .to("TWO", "two@host.com")
        .build();
```

The email object can be build without problems and gets send. The mail server then rejects the message telling the the header `CC` occurs more than one time. The recipients need to be a comma separated list value within only one `CC` header.

This bug also applies to the `cc(…)` and `bcc(…)` methods.

I rewrote my code using `email.addRecipient(mailBoxName(mailbox), to, TO)`, then it works as expected.

It would be great to use the fluent API for that also and having a RFC compliant mail composed from it.

**Comment by bbottema** [comment] 2016-02-05 11:58
Check, will look into it soon

**Comment by bbottema** [comment] 2016-02-18 10:00
@holgerstolzenberg, I didn't test it yet but when I look at the code of the [fluent Builder](https://github.com/bbottema/simple-java-mail/blob/master/src/main/java/org/codemonkey/simplejavamail/Email.java#L400), it uses the same methods to add the addresses as when you do it manually. I'm not sure how your problem arises.

**Comment by holgerstolzenberg** [comment] 2016-02-18 13:44
I´ll try to look into it...

**Comment by bbottema** [comment] 2016-02-19 09:17
I've tried your example with a combination of cc's and bcc's, but I'm unable to reproduce the problem. I'm closing this ticket, but please reopen it if you still think it's an issue with simple-java-mail.

**Closed by bbottema** 2016-02-19 09:17 UTC
Labels: bug, Priority-High
