### ISSUE TITLE
NullPointer in org.simplejavamail.api.email.AttachmentResource.getDataSource()

### ISSUE THREAD

**Issue by Zershmettaling** [bbottema/simple-java-mail#426] opened 2022-12-01 12:47 UTC
Hi Benny, you did a fantastic job, really nice library your Simple Java Mail :-)

I'm working with your SMIME extension, testing different scenarios.
Use case: I created an **encrypted** mail **without signature** and sent it to me.
Then I fetched it from server and read this mail as MIME message (using EmailConverter.emlToEmail with my Pkcs12Config).

Following occurs in log:
```
DEBUG  (SMIMESupport.java:191) checking for S/MIME signed / encrypted attachments...
DEBUG  (SMIMESupport.java:233) decrypting S/MIME signed attachment 'smime.p7m'...
WARN   (SMIMESupport.java:332) S/MIME signed content type not recognized, please raise an issue for class java.lang.String
java.lang.NullPointerException: Cannot invoke "org.simplejavamail.api.email.AttachmentResource.getDataSource()" because "attachment" is null
	at org.simplejavamail.internal.smimesupport.SMIMESupport.isMimeMessageAttachment(SMIMESupport.java:206)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.decryptAttachments(SMIMESupport.java:198)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.decryptAttachments(SMIMESupport.java:139)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.decryptAttachments(SMIMESupport.java:94)
	at org.simplejavamail.converter.EmailConverter.decryptAttachments(EmailConverter.java:258)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:136)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:122)
	at org.simplejavamail.converter.EmailConverter.emlToEmailBuilder(EmailConverter.java:390)
	at org.simplejavamail.converter.EmailConverter.emlToEmail(EmailConverter.java:319)
```

Sending the same mail **with signature** works fine.

**Comment by bbottema** [comment] 2022-12-14 20:20
Hmm, I just did a local test with Wiser SMTP server for testing, but I can't reproduce this. I just encrypted, sent, received and decrypted the message but had no issue reading the email back.

Can you help me reproduce this issue?

**Comment by Zershmettaling** [comment] 2022-12-15 14:55
I didn't use SMTP/POP3 in this case, just plain MIME content pushed into EmailConverter.emlToEmail which works fine as long as signature is included if encryption is enabled. Stepping into your sources shows that "SMIMESupport.isMimeMessageAttachment" throws a NPE because no attachments have been decrypted:
![grafik](https://user-images.githubusercontent.com/119598241/207892597-2d01f325-80fa-4f53-a066-ab80edadd804.png)

Maybe signature is handled as attachment in any case but cannot be decrypted and leads to this problem...

**Comment by bbottema** [comment] 2022-12-15 16:08
This is one of the most challenging parts of the code base due to the recursive nature of nested (signed/encrypted) emails and how signed emails should be merged to get a single result.

Could you possibly share or privately email me the MimeMessage EML file? It's impossible for me to analyse otherwise.

**Comment by Zershmettaling** [comment] 2022-12-16 11:34
Unfortunately this doesn't work as you would need my private key to be able to decrypt the content and I cannot give these files as they contain sensible information of me and my work, sorry, thats the nature of encryption.
Maybe you can add a null check in "isMimeMessageAttachment" method instead ?

Do you have access to MS Graph API ? There you can read encrypted messages as MIME message directly, thats what I did. Send a message to your MS mail account and enable encryption only without signature to get error case. See [https://learn.microsoft.com/en-us/graph/outlook-get-mime-message](url)

Sorry that I cannot provide you with example data directly, getting these testing scenarios can be time consuming, I know.
Best wishes

**Comment by bbottema** [comment] 2022-12-25 13:34
I can add a null-check, but I'm not sure what we're fixing here. Sounds more like a silent fail and continue.

**Comment by bbottema** [comment] 2023-02-20 16:26
No, I don't have access to MS Graph.

> Unfortunately this doesn't work as you would need my private key to be able to decrypt the content and I cannot give these files as they contain sensible information of me and my work, sorry, thats the nature of encryption.

Well, I actually meant if you could do that using a dummy key you can share. I'm not even able to encrypt without signing using standard Java (Bouncycastle) libraries. It's actually a [discouraged practice](https://security.stackexchange.com/questions/202539/smime-is-encrypting-reply-to-a-signed-mail-without-own-cerificate-possible#comment406303_202553) to encrypt without signing. However, I do think Simple Java Mail should be able to handle these edge cases.

**Closed** 2023-10-16 11:51 UTC
Labels: Priority-Medium, need-user-input, needs-research, will close soon
