### ISSUE TITLE
Outlook MSG to EML String Parses "Content-ID" Incorrectly

### ISSUE THREAD

**Issue by darb1353** [bbottema/simple-java-mail#307] opened 2021-03-15 21:14 UTC
Hello,

This is the workflow I'm attempting to achieve using Simple Java Mail:
1) Save Outlook MSG
2) Convert Outlook MSG to EML string
3) Save EML String to .eml file
4) Re-open .eml file in Outlook
5) See the same file

Everything works except for embedded images do not parse correctly because of the "Content-ID" not being set correctly. I believe.

The issue manifests as such:
Given this email in Outlook with an embedded image:
![image](https://user-images.githubusercontent.com/4064137/111221034-fb795e80-85a7-11eb-8c44-1b9eca4f2d34.png)

I then run it through this line of code:
`String emlStr = EmailConverter.outlookMsgToEML(file);`

I then save out the "emlStr" to a file and open it in Outlook to see this:
![image](https://user-images.githubusercontent.com/4064137/111221254-3e3b3680-85a8-11eb-96ad-ed048b750b14.png)

Basically, the file is now attached and not embedded. And it can't be found because of a filename change.

The reason I think the problem lies in the "Content-ID" is because of this in the EML file script, I see this:
![image](https://user-images.githubusercontent.com/4064137/111221563-a9850880-85a8-11eb-8d79-f9557336176d.png)
The HTML email is there with the `<img>` tag and `src="cid:image001.png@01D719B4.37AF4500"` 
However, notice the line `Content-ID: <image001.png@01D719B4>`
It's missing the last part of the src name from the img tag. In looking at your source, this seems to happen [here](https://github.com/bbottema/simple-java-mail/blob/492013d4f58ed29598e88f6aab153f54305cc69d/modules/simple-java-mail/src/main/java/org/simplejavamail/converter/internal/mimemessage/MimeMessageHelper.java#L246) in your source.

Why do you strip the file's extension type off the resource name for Content ID? 

What are your thoughts? Am I doing something wrong in using your library?

This is one of my first times doing this, if I should submit this in a different format, please let me know.

**Comment by bbottema** [comment] 2021-03-15 21:20
This behaviour stems from the attachment detection algorithm, which deals with extensions in a certain way. Obviously this is a bug you found, so thank you for bringing it up!

I'll take a closer look in the next few days.

**Comment by bbottema** [comment] 2021-03-21 14:04
Can you provide a sample email so I can reproduce the exact problem? That would help me a lot.

**Comment by darb1353** [comment] 2021-03-22 15:27
Here is the example email from my initial post. Just an email with an embedded image.
[EmbeddedPicture.zip](https://github.com/bbottema/simple-java-mail/files/6183363/EmbeddedPicture.zip)

**Comment by bbottema** [comment] 2021-04-10 12:32
I found the cause and fixed it promptly. Released in v6.5.1!

**Closed by bbottema** 2021-04-10 12:32 UTC
Labels: Priority-Medium, bug
