### ISSUE TITLE
Executor settings passed to the builder are ignored

### ISSUE THREAD

**Issue by andrus** [bbottema/simple-java-mail#262] opened 2020-05-03 09:45 UTC
I am integrating Simple Java Mail to the [Bootique framework](https://bootique.io/). It works great otherwise, but I noticed a [small inconsistency](https://github.com/bootique/bootique-simplejavamail/blob/master/bootique-simplejavamail/src/main/java/io/bootique/simplejavamail/MailerFactory.java#L64). If I assemble the mailer like this:

```java
MailerRegularBuilderImpl builder = MailerBuilder
    .withSMTPServer(resolveSmtpServer(), resolveSmtpPort())
    .withThreadPoolSize(5)
    .withThreadPoolKeepAliveTime(10);
```

Custom `threadPoolSize` and `threadPoolKeepAliveTime` are ignored, as the internal ExecutorService is resolved in `MailerGenericBuilderImpl` constructor, prior to those properties being redefined. 

I found a workaround, which is to configured ExecutorService on my own, and pass it over to `.withExecutorService`. So while this is not an immediate issue for Bootique, I still figured I'd mention it here.

**Comment by bbottema** [comment] 2020-05-03 11:48
Thanks for the report. I would say this is by design though, like using `.withExecutorService(..)` indicates that you as a user want full control of how threads are handled. I was sure I mentioned it in the Javadoc, but it seems I forgot to mention this.

Any thoughts on this?

**Comment by bbottema** [comment] 2020-05-03 11:49
Thank you for reporting this. Will look into it asap.

**Comment by bbottema** [comment] 2020-05-03 12:40
Fix released in 6.0.4.

**Closed by bbottema** 2020-05-03 12:40 UTC
Labels: Priority-High, bug

**Comment by andrus** [comment] 2020-05-03 12:43
Thanks for the quick turnaround. Looking forward to 6.0.4

**Comment by bbottema** [comment] 2020-05-03 12:45
Should be in Maven Central in a few minutes

**Comment by andrus** [comment] 2020-05-03 13:17
Already is. Works like a charm. Thanks!
