### ISSUE TITLE
Smime exception

### ISSUE THREAD

**Issue by lmpampaletakis** [bbottema/simple-java-mail#342] opened 2021-10-14 21:48 UTC
Hi want to send a signed email, but I am getting an error.

The config I have used is:
```

Pkcs12Config myKeyInfo = Pkcs12Config.builder()
                .pkcs12Store(SimpleMailMain.class.getClassLoader().getResourceAsStream("pk.p12"))
                .storePassword("****")
                .keyAlias("pk")
                .keyPassword("****")
                .build();

 Email email = EmailBuilder.startingBlank()
                    .withDispositionNotificationTo().withReturnReceiptTo().signWithSmime(myKeyInfo)
                    .from("test@test.com").bcc(lala@lala.com)
                    .withSubject("Signed mail")
                    .withHTMLText("<b>Hi</b>, Test!!!")
                    .buildEmail();
                    
 Mailer.sendMail(email);
```
The key is a pfx.

Exception in thread "main" net.markenwerk.utils.mail.smime.SmimeException
	at net.markenwerk.utils.mail.smime.SmimeUtil.handledException(SmimeUtil.java:615)
	at net.markenwerk.utils.mail.smime.SmimeUtil.sign(SmimeUtil.java:331)
	at net.markenwerk.utils.mail.smime.SmimeUtil.sign(SmimeUtil.java:411)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.signMessage(SMIMESupport.java:474)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.signAndOrEncryptEmail(SMIMESupport.java:462)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageProducer.populateMimeMessage(MimeMessageProducer.java:99)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageProducerHelper.produceMimeMessage(MimeMessageProducerHelper.java:57)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:69)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331)
	at com.simple.mail.SimpleMailMain.send(SimpleMailMain.java:68)
	at com.simple.mail.SimpleMailMain.sendSimpleMail(SimpleMailMain.java:50)
	at com.simple.mail.SimpleMailMain.main(SimpleMailMain.java:25)
Caused by: java.lang.NullPointerException
	at net.markenwerk.utils.mail.smime.SmimeUtil.getCertificateStore(SmimeUtil.java:381)
	at net.markenwerk.utils.mail.smime.SmimeUtil.getGenerator(SmimeUtil.java:339)
	at net.markenwerk.utils.mail.smime.SmimeUtil.sign(SmimeUtil.java:324)
	... 12 more

**Comment by bbottema** [comment] 2021-12-25 21:10
Unable to reproduce the problem, closing until that changes.

**Closed by bbottema** 2021-12-25 21:10 UTC
Labels: need-user-input
