### ISSUE TITLE
Generated Threads Go to a TIMED_WAITING state and never die

### ISSUE THREAD

**Issue by fmcorp** [bbottema/simple-java-mail#371] opened 2022-01-05 19:43 UTC
AdoptOpenJDK 1.8 x32
Statically run app that generates many emails using simpleJavaMail v 6.7.5.   

Example Program that exhibits the issue attached.

[TestEmail.txt](https://github.com/bbottema/simple-java-mail/files/7817397/TestEmail.txt)

**Comment by bbottema** [comment] 2022-01-06 09:55
Does this only happen op AdoptOpenJDK? Would you try Oracle JDK please?

**Comment by fmcorp** [comment] 2022-01-06 14:59
I switched to OracleJDK 1.8 and got the same result.

All emails are being sent and delivered correctly.  But the JVM never dies.  While profiling the app, simpleJavaMail creates new threads for each call.  The threads never die.
***@***.***

**Comment by bbottema** [comment] 2022-01-09 11:05
So I performed this test with the code from your text file as-is, using Google mail and I cannot reproduce your issue.

![image](https://user-images.githubusercontent.com/2115718/148679552-038c2d22-aba5-41ea-94de-a07de2ac2039.png)

![image](https://user-images.githubusercontent.com/2115718/148679539-fcb00f02-8bf6-4024-a7dc-5593713cde2f.png)

**Comment by bbottema** [comment] 2022-01-09 11:19
Right now there's nothing I can do here. Closing until there's more to go on...

**Closed by bbottema** 2022-01-09 11:19 UTC
Labels: invalid, need-user-input
